excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://rumberg.github.io
name: PR for Developers
description: I'm not a good developer, but I know how to bring tech projects and companies to a large global audience through PR. My clients include Stack Overflow, Udacity, 6Wunderkinder (before they've been bought by Microsoft), Blinkist and many others.<br /><br />Happy to help!
author: Sebastian Rumberg
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 